#!/bin/bash
set -e


#Attention cette partie supprime le contenu de l conf à chaque reinstallation ! c'est un bug !
# Demande à l'utilisateur son nom d'utilisateur
#if [ -f "$HOME"/.afs/afs_configuration.conf ]; then
    #USERNAME=$(grep USER "$HOME"/.afs/afs_configuration.conf | cut -d= -f2)
#    echo "Un fichier de configuration est déja présent."
#else
#    USERNAME=$(whiptail --inputbox "Veuillez entrer votre nom d'utilisateur (prenom.nom) de votre compte EPITA :" 10 60 3>&1 1>&2 2>&3)
#    if [ $? -ne 0 ]; then
#        echo "Installation annulée."
#        exit 1
#    fi
#fi

USERNAME=$(whiptail --inputbox "Veuillez entrer votre nom d'utilisateur (prenom.nom) de votre compte EPITA :" 10 60 3>&1 1>&2 2>&3)
    if [ $? -ne 0 ]; then
        echo "Installation annulée."
        exit 1
    fi
  
# Demande à l'utilisateur le chemin distant
#REMOTE_PATH=$(whiptail --inputbox "Veuillez entrer le chemin distant:" 10 60 3>&1 1>&2 2>&3)
#if [ $? -ne 0 ]; then
#    echo "Installation annulée."
#    exit 1
#fi

# Enregistrement des données dans un fichier de configuration
if [ -d "$HOME/.afs/" ]; then
  mkdir "$HOME/.afs/"
fi
echo "USERNAME=$USERNAME" > "$HOME/.afs/afs_configuration.conf"
#echo "REMOTE_PATH=$REMOTE_PATH" >> "$HOME/.afs/afs_configuration.conf"

exit 0
