#!/bin/bash
set -e

function message {
  (whiptail --title "Installation" --msgbox "$1" 10 60 )
}

#Attention cette partie supprime le contenu de la conf à chaque reinstallation ! c'est un bug !
# Demande à l'utilisateur son nom d'utilisateur
if [ -f "$HOME/.afs/configuration.conf" ]; then
    USERNAME=$(grep USER "$HOME/.afs/configuration.conf" | cut -d= -f2)
    echo "Un fichier de configuration est déja présent."
else
    USERNAME=$(whiptail --title "Installation" --inputbox "Veuillez entrer votre nom d'utilisateur (prenom.nom) de votre compte EPITA :" 10 60 3>&1 1>&2 2>&3)
    if [ $? -ne 0 ]; then
        echo "Installation annulée."
        exit 1
    fi
fi

#AUTOCONNEXION=$(whiptail --title "Configuration" --yesno "Voulez-vous vous connecter à l'ouverture de votre session ?"10 60 3>&1 1>&2 2>&3)

#if AUTOCONNEXION = yes ; then
  #/etc/init.d
#  touch "/etc/ini.d/afs.sh"
  
#fi

#Configuration du SSH, requis pour la connexion aux serveur d'EPITA 
# ( pour plus d'info voici le blog du CRI "https://blog.cri.epita.fr/post/2020-10-30-migration-realm-kerberos/" )
echo "Configuration SSH..."
SSH_CONFIG="$HOME/.ssh/config"
# Vérifie si le fichier de configuration existe, sinon le crée
if [ ! -f "$SSH_CONFIG" ]; then
    touch "$SSH_CONFIG"
fi
HOST_CONFIG="Host git.cri.epita.fr
      GSSAPIAuthentication yes
    
    Host ssh.cri.epita.fr
      GSSAPIAuthentication yes
      GSSAPIDelegateCredentials yes
      "

if grep -Fxq "Host" "$SSH_CONFIG"; then
    echo "Le SSH et déja configuré sur : $SSH_CONFIG. Aucune action requise."
else
    echo "Configuration du SSH : $SSH_CONFIG."
    # Ajoute l'entrée au fichier de configuration
    echo "$HOST_CONFIG" >> "$SSH_CONFIG"
    echo  "La configuration a été rajoutée."

fi
echo -e "\033[32m SSH configuré. \033[0m"
 

# Enregistrement des données dans un fichier de configuration
if [ ! -d "$HOME/.afs" ]; then
  mkdir "$HOME/.afs"
  if [ ! -f "$HOME/.afs/configuration.conf" ]; then
    touch "$HOME/.afs/configuration.conf"
  fi
fi

echo "USERNAME=$USERNAME" >> "$HOME/.afs/configuration.conf"
(whiptail --title "Installation" --msgbox "Installation terminée." 10 60)

