name: afs-connexion           # Nom de l'application Snap
version: '1.0'                # Version du paquet
summary: Connexion automatique à l'AFS
description: |
  Un outil pour se connecter automatiquement à l'AFS avec vérification des dépendances et génération de tickets Kerberos.
confinement: strict           # Niveau de confinement (strict, devmode, classic)

grade: stable                 # Niveau de stabilité (stable, devel)
base: core20                  # Base du snap (core, core18, core20, core22, ...)

parts:
  afs-connexion:
    source: ./src             # Indique le dossier où sont situés les fichiers
    source-type: local
    plugin: dump              # Simplement copier les fichiers du projet
    stage-packages:           # Ajouter des dépendances si nécessaire
      - whiptail
      - sshfs
      - krb5-user
    organize:
      "afs_connexion_script.sh": "bin/afs_connexion_script.sh"
      "afs_configuration.sh": "bin/afs_configuration.sh"
      "gui/logo.png": "meta/gui/logo.png"

hooks:
  install:
    plugs: [network]          # Ajoute des permissions nécessaires

apps:
  afs-connexion:
    command: bin/afs_connexion_script.sh
    desktop: ./gui/afs.desktop
    environment:
      SNAP_APP_CONFIG: $SNAP/config.cfg
    plugs:
      - home
      - network
      - network-bind
